### PR TITLE
ingtegrate object Models

### PR DESCRIPTION
**Pull request by bumbledog**
Small changes to the graphics objects to make 2D camera implementation easier.
Nothing from object models changed - but put in a container object and is now working more closely and intuitively with the gameloop

### CODE REVIEW

**Comment by aaronlamchops** [comment]
Kylee, did you pull from master after my pull request was merged into master? If not, you should because i think your branch is one commit behind master. I was looking at the graphics.js that you are about to push and it doesnt have the changes that i made. I fear that if this branch is merged into master, we will lose some lines of code.

**Comment by aaronlamchops** [comment]
Oh nevermind!!! I wasnt looking hard enough. hahaha

**Review by aaronlamchops — APPROVED** [review]
Looks good. I like the new objects model. I couldnt see a real reason for creating a:
var width = 0;
var height = 0;
In the graphics.js, because we can just call Canvas.width or Canvas.height where we need them in the module since Canvas is not undefined in the rest of the function. As long as that.initialize is called before the rest of the functions(which it should be), i dont think we need the definition of width and height in the graphics.js

**Comment by bumbledog** [comment]
Yeah, I was one commit behind but I believe I fixed everything when I looked at the merge conflicts

**Comment by bumbledog** [comment]
Fair enough. We can switch that. I wrote this before you made the canvas object accessable through the object, so that wasn't an option

**Pull request merged**
