### PR TITLE
general camera fixes

### PR DESCRIPTION
**Pull request by bumbledog**

### CODE REVIEW

**Comment by aaronlamchops** [comment]
I believe that this pull request is behind our latest merges. I think this pull request is missing some lines of code from master. You might need to pull from master and retry on this one.

**Comment by bumbledog** [comment]
Check it again, I edited the pull request after the other one merged. I don't see anything from master getting deleted in my files changed and my code says I'm up to date when I try to pull -- where can I check for that to be sure?

**Comment by bumbledog** [comment]
Merging did nothing... I believe that git keeps track of things in most so that if you are behind a few commits it automatically adds the new stuff when you merge. I'll be more careful though - it is a good idea to stay on track of changes.

**Comment by aaronlamchops** [comment]
Sorry again... I wasnt looking hard enough again... I didnt see the view changes button down the line. I was only looking at the previous code before the merge. 

Looks good!

screen shot 2017-04-06 at 5 53 25 pm

**Review by aaronlamchops — APPROVED** [review]
Looks good. I like the small changes.

**Pull request merged**
